### ISSUE TITLE
Spatial statistics node settings are not backward compatible

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#103]
Because of the introduction of the VariableSettings class in this [commit](https://github.com/spatial-data-lab/knime-geospatial-extension/commit/ff41b1dafcdc9a0f422ff75ad75a758ec3520d3b) the node settings are no longer loaded. Using a settings class changes the settings structure by introducing another sub config for the class.
We need to ensure that existing node can still be loaded. So I would suggest to revert the VariableSettings related changes.

**Comment by wybert** [comment]
Do you think it is worth keeping the VariableSettings class since it will make the code base easier to maintain? The node can be easily re-dragged to the canvas and replaced with the old node. We can make an announcement about this when 1.1 come out. It will make it easier to add more spatial statics nodes.

**Comment by wybert** [comment]
> 

Hi @koettert, have you gotten a response from the Knime Python team?
