### ISSUE TITLE
Polish the description in Spatial Weights node 

### ISSUE THREAD

**Issue by UrbanGISer** [spatial-data-lab/knime-geospatial-extension#137]
Please polish the descriptions
such as specifying the matching relationship between the  weight category and the following options

e.g. Threshold - > Threshold ( For Binary Distance Band/Inverse Distance) 

Power - >Power (  for Inverse Distance)
 
Nearest k  - > K ( for Nearest K)
 

**these are the same contents**

Threshold
Distance band weights are often used for point data. The weights within the threshold are 1 and otherwise 0. Inverse distance weights are often used for point data. The weights within the threshold are distance^-power, and otherwise 0. The distance is Euclidean distance.
Power
Distance band weights are often used for point data. The weights within the threshold are 1 and otherwise 0. Inverse distance weights are often used for point data. The weights within the threshold are distance^-power, and otherwise 0. The distance is Euclidean distance.

**what are rows and columns for ?** 

Rows
Please choose your rows and colunns of your lattice.
Columns
Please choose your rows and columns of your lattice.

**No  kernel Introduction in Nearest K part** 

Kernel K
The number of nearest neighbors to use for determining bandwidth.
Kernel bandwidth
The bandwidth of the kernel. The default is fixed. If adaptive then bandwidth is adaptive across observations.

**Comment by wybert** [comment]
- [x] Let the user optionally select a column in the Spatial Weight node that should be used as ID column. If an ID column is selected the focal and neighbor column will output the ID column value instead of the row index.

- [ ] The spatial modelling nodes that consume the spatial weights table will also allow the user to optionally select an ID column. If not selected the node will use the row index as before. The node internally will take care of mapping the id values to the corresponding indices as needed.
