### ISSUE TITLE
Allow Spatial Weight to use Long Datatype column as ID column

### ISSUE THREAD

**Issue by UrbanGISer** [spatial-data-lab/knime-geospatial-extension#230]
version 1.1 can not allow the user to choose the column with Long datatype as the Spatial weight ID column

**Comment by UrbanGISer** [comment]
I just revise the  is_int to contain         knext.int32(),        knext.int64(),

```
def is_int(column: knext.Column) -> bool:
    """
    Checks if column is int
    @return: True if Column is numeric
    """
    return column.ktype in [
        knext.int32(),
        knext.int64(),
    ]
```

**Comment by koettert** [comment]
Can you please ask Xiaokang if this changes is ok. As far as I remember we
changed support for long to int only but I do but recall the reason.

--

**Comment by wybert** [comment]
Hi @koettert, I think @UrbanGISer Changed the `is_int` and `is_int_or_string` functions in the utils. It will affect all the nodes which using it. 

For the `spatial weight`, I convert `id_col` into `int` in Python. Notice that Python 3 does not have a fixed size for integers. It supports unlimited precision integers, that is what the int means in Python. However, Numpy has int32 and int64. 

In this case, it should be good with the `spatial weight` node since I did use the int type in Python. It should be good for all other nodes if the nodes pass the test.
