### ISSUE TITLE
Document how to setup custom executor with the Geospatial Extension for KNIME Business Hub

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#327]
Create a step by step guide referencing as much of existing documentation. Explain the difference between airgap and online installation.

**Comment by sturmkev** [comment]
I created a first draft. Please read through it and comment on all sections that don't make sense from the perspective of an less experienced user.
[geospatial-install.md](https://github.com/spatial-data-lab/knime-geospatial-extension/files/14431308/geospatial-install.md)

**Comment by sturmkev** [comment]
There is an updated version available.
[geospatial-install.md](https://github.com/spatial-data-lab/knime-geospatial-extension/files/14434321/geospatial-install.md)

We might need to talk about how to fix the embedding of images.

**Comment by wybert** [comment]
Great work. I can't see the image embedded in the markdown file. I would suggest give a bit more details on the last step. Maybe give a link about the steps about create the EC in KNIME Hub.

**Comment by sturmkev** [comment]
Thank you. Good point that you mention to link our docs for the last step; will include that as well.
I figured that the screenshots are not visible, since they don't live somewhere online. Maybe someone of you knows how to integrate those in the file?

**Comment by wybert** [comment]
You need host the screenshots somewhere so that you can just put the image URL in markdown file like `![](image_url.png)`. We can host the image in Github and then past the raw image URL in the markdown file, see [here](https://github.com/spatial-data-lab/knime-geospatial-extension/blob/main/docs/sptial_weights.md) as an example.

I am wondering if we could include Python env and custom executor profiles setup here.

**Comment by sturmkev** [comment]
Hm, why exactly would you like to have conda envs and custom executor profiles described in this guide?
I have the feeling that this would be out of scope for just setting up the extension on an execution context.

Thank you for the example about the images for markdown files. Totally clear to me.
Since I haven't used git yet to push my guide, I suggest I will just zip the md + images and you can take care of placing it at the right spot in our repository!?

**Comment by sturmkev** [comment]
This is the most recent version.
[geospatial-install-guide.zip](https://github.com/spatial-data-lab/knime-geospatial-extension/files/14495792/geospatial-install-guide.zip)

**Comment by koettert** [comment]
I will crate a branch in Github with the above attached file as source of truth. I will then let Daria double check the spelling etc.
