### ISSUE TITLE
Geocoding support

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#39]
As a user I want to get the geo coordinates of an address. To do so I want to use a free provider such as OSM but also commercial once such as here.com or Google.
The input of the node would be a table with the address information and the node would append a new column to each row with the geo coordinates of the corresponding address.

**Comment by koettert** [comment]
We might be able to use the https://geopy.readthedocs.io/en/stable/ library for this

**Comment by koettert** [comment]
@wybert just had a look at the node by executing the testworkflow and found several issues:

- Node should return a geometry columns instead of latitude and longitude column. This would also save the second call to the API
- Configure should return output table spec with unique result column name. For an example see [here](https://github.com/spatial-data-lab/knime-geospatial-extension/blob/main/knime_extension/src/nodes/calculation.py#L67)
- Default service_provider value is wrong since the keys are all lower case
- Improve node description e.g. state that API key is optional depending on the selected service, add examples on how the address could/should look like
- I would suggest to use an enum with a selection of most common services instead of geopy.geocoders.SERVICE_TO_GEOCODER.keys(). This way we can handle service specific parameters if required e.g. if API key is needed or not e.g. using nominatim now fails with __init__() got an unexpected keyword argument 'api_key'. We can also add more info e.g. the link to the service a nicer user facing name e.g. OpenStreetMap vs Nomatim and maybe a flag if it is free or commercial
- Create a test for each search service
- Icon is missing

**Comment by wybert** [comment]
@UrbanGISer I may need your help for the icons

**Comment by UrbanGISer** [comment]
icons added; geometry columns returned

**Comment by wybert** [comment]
- [x] Node should return a geometry columns instead of latitude and longitude column. This would also save the second call to the API
- [ ] Configure should return output table spec with unique result column name. For an example see [here](https://github.com/spatial-data-lab/knime-geospatial-extension/blob/main/knime_extension/src/nodes/calculation.py#L67)
- [x] Default service_provider value is wrong since the keys are all lower case
- [x] Improve node description e.g. state that API key is optional depending on the selected service, add examples on how the address could/should look like
- [x] I would suggest to use an enum with a selection of most common services instead of geopy.geocoders.SERVICE_TO_GEOCODER.keys(). This way we can handle service specific parameters if required e.g. if API key is needed or not e.g. using nominatim now fails with init() got an unexpected keyword argument 'api_key'. We can also add more info e.g. the link to the service a nicer user facing name e.g. OpenStreetMap vs Nomatim and maybe a flag if it is free or commercial
- [x] Create a test for each search service
- [x] Icon is missing

**Comment by koettert** [comment]
Can you please change the enum to include more information as used[ here](https://github.com/spatial-data-lab/knime-geospatial-extension/blob/main/knime_extension/src/nodes/spatialtool.py#L30)
The description of each enum entry should contain a short description and a link to the page where one can obtain the API key from. Ideally the enum contains the logic to obtain the service provider or that returns the necessary arguments for the `service_provider()` call. This method could have the `geocoding_service_settings` as input. This way it would be easier to extend the list and avoid code duplication e.g. in line 697-703 and 787-794

**Comment by koettert** [comment]
Also please use the same logic in configure as [here](https://github.com/spatial-data-lab/knime-geospatial-extension/blob/main/knime_extension/src/nodes/calculation.py#L58) to auto set the geo column and make sure that the result column is unique e.g. address. Please note that you need to do the unique column name also in execute since configure and execute run in different processes that do not share variables.

**Comment by koettert** [comment]
Can you please add AzureMaps, HEREv7, MapBox, and TomTom to the list of supported geocodes since they are well known.

**Comment by wybert** [comment]
> 

I am confusing what configure do actually
